# Clase 2

```{r}
numero <- readline(prompt = "Ingrese un numero: ")
as.numeric(numero)

if (numero > 0) {
  print("El numero es positivo")
} else if (numero < 0) {
  print("El numero es negativo")
} else {
  print("El numero es cero")
}
```

## Ejercicio 2:

```{r}
primer_numero <- readline(prompt = "Ingrese el primer numero: ")
segundo_numero <- readline(prompt = "Ingrese el segundo numero: ")
if (primer_numero > segundo_numero) {
  print("El primer numero es mayor que el segundo")
} else if (primer_numero < segundo_numero) {
  print("El primer numero es menor que el segundo")
} else {
  print("El primer numero es igual que el segundo")
}

```

## Ejercicio 3

```{r}
for (i in 1:5) {
  print(i)
}
```

## Ejercicio 4

```{r}
suma <- 0
for (i in 1:100){
  suma <- suma+i
}
print(suma)
```

## Ejercicio 5 y 6

#### El promedio es la division de n valores sumados entre sí

#### Necesitariamos: Saber cuantos valores hubo (una variable contador y luego sumarlos a todos (la suma ya esta solo falta el count y dividirlo por ese count))

```{r}
suma <- 0
contador <- 0
while(TRUE){
  valor <- as.numeric(readline("Ingrese un número positivo, cuando ingrese un número negativo el programa se detiene: "))
  
  if (valor < 0) {
    break
  }
  contador <- contador + 1
  suma <- valor + suma
  promedio <- suma / contador
  
}
cat("La suma de los numeros positivos fue de: ", suma)
cat("El promedio de los números positivos fue de: ", promedio)
```

## Funciones

### Ejercicio 7 y 8

```{r}
cuadrado <- function(x, invertir = FALSE){
  resultado <- x^2
  if(invertir == TRUE){
    resultado <- -resultado
  }
  return(resultado)
}

cuadrado(10, TRUE)
```

## Funciones recursivas
#### Deben tener un caso base de parada
### Ejercicio 9
```{r}
factorial_recursivo <- function(x){
  if (x <= 1) {
    return(1)
  } else {
    return(x * factorial_recursivo(x-1))
  }
}

factorial_recursivo(10)
```

### Ejercicio 10 (?
```{r}
numero1 <- as.numeric(readline("Ingrese un número: "))
numero2 <- as.numeric(readline("Ingrese otro número: "))

suma <- numero1 + numero2
if(suma > 0) {
  print("La suma es positiva")
} else if (suma < 0) {
  print("La suma es negativa")
} else {
  print("La suma es cero")
}
```